compatibility_date = "2024-01-01"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = false
logpush = true
tail_consumers = [
  {service = "engine-tail-consumer"},
  {service = "engine-staging-tail-consumer"},
  {service = "engine-tail"}
]

[env.production]
name = "engine"
logpush = true
route = { pattern = "engine.solomon-ai-platform.com/*", zone_name = "solomon-ai-platform.com" }

kv_namespaces = [
  { binding = "KV", id = "019720a586c448c2a88a58773da08fd8" }
]

mtls_certificates = [
  { binding = "TELLER_CERT", certificate_id = "c82877a0-409e-4589-a935-ca220531651f" }
]

r2_buckets = [
  { binding = "STORAGE", bucket_name = "engine-assets", preview_bucket_name = "" }
]

[env.production.queues]
producers = [
  { queue = "user-actions-production", binding = "USER_ACTIONS" },
]

consumers = [
  { queue = "user-actions-production", max_batch_size = 10, max_retries = 10, dead_letter_queue = "user-actions-production-dlq" },
  { queue = "user-actions-production-dlq", max_batch_size = 10, max_retries = 10 },
]

[env.production.observability]
enabled = true
head_sampling_rate = 0.1 # 10% of requests are logged

[[env.production.d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "engine-production-db"
database_id = "7e9430cd-517d-4139-bb27-1be427d3474a"

[env.staging]
name = "engine-staging"
route = { pattern = "engine-staging.solomon-ai-platform.com/*", zone_name = "solomon-ai-platform.com" }

kv_namespaces = [
  { binding = "KV", id = "6745cb3ad41e4d35a45bf67bb515c08b" }
]

mtls_certificates = [
  { binding = "TELLER_CERT", certificate_id = "c82877a0-409e-4589-a935-ca220531651f" }
]

r2_buckets = [
  { binding = "STORAGE", bucket_name = "engine-assets", preview_bucket_name = "" },
  { binding = "R2", bucket_name = "bank-statements", preview_bucket_name = "" }
]

[env.staging.observability]
enabled = true
head_sampling_rate = 0.1 # 10% of requests are logged

[[env.staging.d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "engine-staging-db"
database_id = "4d7f64be-60e6-44ad-9b7a-5e499dfec52c"

[env.staging.queues]
producers = [
  { queue = "user-actions-staging", binding = "USER_ACTIONS" },
]

consumers = [
  { queue = "user-actions-staging", max_batch_size = 10, max_retries = 10, dead_letter_queue = "user-actions-staging-dlq" },
  { queue = "user-actions-staging-dlq", max_batch_size = 10, max_retries = 10 },
]

# local
[[env.local.d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "engine-db"
database_id = "50694d1f-d468-4807-a60f-3e3c9287781e"