name: Preview Deployment - Engine
env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
  TIPTAP_PRO_TOKEN: ${{ secrets.TIPTAP_PRO_TOKEN }}
  SOLOMON_AI_TOKEN: ${{ secrets.SOLOMON_AI_TOKEN }}
  
on:
  push:
    branches-ignore:
      - main
    paths:
      - services/financial-service/**
  workflow_dispatch:

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      # - name: 🔦 Run linter
      #   run: bun run lint
      #   working-directory: ./services/financial-service
      # - name: 🪐 Check TypeScript
      #   run: bun run check:types
      #   working-directory: ./services/financial-service
      # - name: 🧪 Run unit tests
      #   run: bun test
      #   working-directory: ./services/financial-service
      - name: Deploy Project Artifacts to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: bun
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "services/financial-service"
          wranglerVersion: "3.76.0"
          command: deploy --minify src/index.ts --env staging
